### ISSUE TITLE
UI+Zoom issues with companion houseing

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#10]
https://github.com/nakano15/terraguardians/assets/89364836/bca1b890-833e-4f12-9779-dadcbbda8367

as you can see here it tends to mess with placeing companion housing

**Comment by nakano15** [comment]
Oops, I didn't knew about that issue. I'll add that to the list of to check.

Ps: Welcome to the ugly box houses club.

**Comment by nakano15** [comment]
Fixed.
