### ISSUE TITLE
Zoom causing text above companions to dupelicate

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#11]
![image](https://github.com/nakano15/terraguardians/assets/89364836/f77fd63c-633d-4ad8-91b6-2d800c7688e5)

**Comment by nakano15** [comment]
Are you bond merged with Leona?

**Comment by AnukWarrior** [comment]
no im not

**Comment by nakano15** [comment]
Well, that's one less bug then, I guess.

**Comment by nakano15** [comment]
Fixed.
