### ISSUE TITLE
the nights edge (and possably other 1.4.4 reworked swords) do no damage and are broken on companions

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#15]
https://github.com/nakano15/terraguardians/assets/89364836/18ee17fd-f93a-43e5-b83d-4958fb19d764

**Comment by AnnoyingGuide** [comment]
This is a known issue that I believe can't be fixed right now.

**Comment by AnukWarrior** [comment]
hmm interesting i think i remember hearing somewhere that speed and or size effects for these 1.4.4 reworked swords might cause them to break but im not sure about that might be worth investigateing tho since companions have diffrant sword sizes depending on their size

**Comment by AnukWarrior** [comment]
wow i think im correct michelle is able to use 1.4.4 nights edge perfectly fine it deals damage and has the new effect i think how this could be fixed is by making speed/size effects added for companions be ignored for these reworked weapons

**Comment by nakano15** [comment]
I'd say that's not the only issue though. Those wings are... Under.
At least do the special effects is expected of the weapons not to do, but dealing no damage is absurdity.
I'll check that out monday.

**Comment by nakano15** [comment]
![image](https://github.com/nakano15/terraguardians/assets/1460392/56816683-3e8a-4d3d-8cdb-9b8b7a27aa7e)
I managed to add the shot script of the sword, so the effect was added.
Beside, there's a lot more weapons that will still need to have its firing scripts reimplemented.
Anyways, fixed.
