### ISSUE TITLE
multiable companions can still be called with the pack leader necklace in use

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#16]
https://github.com/nakano15/terraguardians/assets/89364836/6196b66d-e526-43c5-9b63-367444bf5b2e

**Comment by nakano15** [comment]
I will need to check that out monday too.
Ps:. Giant Floating Ale Mug.

**Comment by nakano15** [comment]
Well, the pack leader necklace changed how it works on 1.4 version.
Now, you can have other companions with you, but only one will be affected by the necklace.
I updated the item description to better reflect its current use.
