### ISSUE TITLE
strange softlock? with mounting a companion at the edge of space

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#17]
pretty much wait for your companion to start grappleing to you ask to mount on them then fly up as it happens outside the worlds border in space

during this i cant interact with anything or even open up the menu to exit the world the only excpection i found was chat 

https://github.com/nakano15/terraguardians/assets/89364836/09334e04-4083-4a23-b55d-a4e51d95c530

**Comment by nakano15** [comment]
I recommend posting here the client log after you trigger that.
If the player softlocks, it's because the game is crashing.

**Comment by AnukWarrior** [comment]
[client.log](https://github.com/nakano15/terraguardians/files/12841707/client.log)
i think this is how i upload the log here?

**Comment by nakano15** [comment]
Indeed. And it gives me some leads as to why it's crashing.
I will investigate that tomorrow. Try avoiding going to the moon meanwhile.

**Comment by nakano15** [comment]
The video actually helped a lot with the solution to the issue. I thought was about Thorium, but actually, was a mix between the mounting animation and the pulling rope causing absurdities to happen with character position.

Thanks for the report. Fixed.
