### ISSUE TITLE
huge fps loss with high number of companions in world on low end machines

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#21]
without terraguardians

https://github.com/nakano15/terraguardians/assets/89364836/b340b667-037b-4a10-bba0-37ce60bc424c

with terraguardians

https://github.com/nakano15/terraguardians/assets/89364836/bd402ecc-c271-4413-80e2-c89d9e309a59

if theres nothing much else you can do to improve the mods performance then perhaps putting a warning on the workshop page that the mod can cause large fps loss on low end machines would be nice

**Comment by nakano15** [comment]
That's actually a known issue somehow, even more since companions inherit Player character.
A thing you could try is control the number of companions living in your world.
I may try seeing if I can lower the processing required by idle companions though.

**Comment by AnukWarrior** [comment]
do you by chance have it so companions ai is massivly simplfiyed when a certain distance away from the player? as even when i have no companions nearby i still get massive frame drops

**Comment by nakano15** [comment]
I will try working on that at some point.
I do believe there's ways of trimming what processing the game does when the companions are away.

**Comment by nakano15** [comment]
I changed some codes regarding town npcs script update on the latest update of the mod.
Check if eased the fps loss.

**Comment by AnukWarrior** [comment]
sadly the update had very little to no effect on improving my performance it may also of had the side effect of breaking wings on companions again as they cant go down platforms with wings again another good side effect of the update is that it did manage to fix the TWAILA companion cursor issue tho

**Comment by AnukWarrior** [comment]
latest update has massively improved my framerates now its still not the best but its actualy alot more playable at full speed on my laptop now
so i supposed this can be closed now thanks for that
