### ISSUE TITLE
companions equipment ui changes colour with players loadout

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#33]
what it normaly looks like on the players first loadout
![image](https://github.com/nakano15/terraguardians/assets/89364836/11b3cc45-7410-4b61-b4c2-79d699de0869)

now what it looks like with the other 2 loadouts
![image](https://github.com/nakano15/terraguardians/assets/89364836/f4788e2f-53a9-4942-a29b-9031fa76c1a3)
![image](https://github.com/nakano15/terraguardians/assets/89364836/95c888ed-04e0-4c87-9b44-f9927cfae48c)

**Comment by nakano15** [comment]
That's just a minor visual issue.
The mod is actually using the same script as the player for equipment slots, so that's why it changes with the loadouts.

I'll be closing since this isn't something game breaking.
