### ISSUE TITLE
autofire setting does not work on bond-merged companions

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#34]
https://github.com/nakano15/terraguardians/assets/89364836/331d1e1f-f121-4965-ab97-56ee74a086ac

**Comment by nakano15** [comment]
I didn't even knew that setting exists. Is that a tModLoader feature or something?
Anyways, I'll be checking that out in a few.

**Comment by nakano15** [comment]
Fixed. Now the Autofire setting will affect companions you're controlling.
