### ISSUE TITLE
companions cant go down platforms with wings again

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#36]
same issue from the past happening again it started to happen again when wrath came back to the mod

**Comment by nakano15** [comment]
I took note of that issue. I'll be messing with it monday.

**Comment by nakano15** [comment]
Seems like a wing specific issue. What wing you gave to that companion?

**Comment by AnukWarrior** [comment]
i used solar wings

**Comment by AnukWarrior** [comment]
actualy now  that i think about maybe its the wing slot mod? dont know why it specificly would break companions going down platforms considering everything else seems to work with wings for them aswell as the fact that in the past companions could go down platforms with wings while that mod was loaded

**Comment by nakano15** [comment]
Nope, was the wing. Certain wings have different behaviour when holding down.
Fixed.
