### ISSUE TITLE
Vladimir sometimes does not render

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#39]
![Capture136](https://github.com/nakano15/terraguardians/assets/89364836/193ee799-d41c-4115-ad6e-fbb414683fcd)
after the update with the changed rendering you did he is now sometimes just not rendering

**Comment by nakano15** [comment]
Oops. Seems like as if a npc is to render a companion, that simply doesn't happen.
I'll log that issue.

**Comment by nakano15** [comment]
![image](https://github.com/nakano15/terraguardians/assets/1460392/a4f63b85-6646-4933-a3a1-8391be9107ef)
Fixed.
