### ISSUE TITLE
Terraguardians ui gets in the way of the mannequin ui

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#41]
same as the previous ui issues 
![image](https://github.com/nakano15/terraguardians/assets/89364836/a3cf2c56-3cc1-4b55-9355-48d6367a521d)

**Comment by nakano15** [comment]
This one might be tricky for one specific reason:
I'm having a hard time trying to find out where the scripts of the mannequins are.

**Comment by nakano15** [comment]
Fixed.

**Comment by nakano15** [comment]
I thought I closed this. Oops.
