### ISSUE TITLE
asking fluffles to lift the player while she is on the players back causes a fast vertical noclip

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#44]
https://github.com/nakano15/terraguardians/assets/89364836/96ed159f-c1f1-4051-a1a5-26009e5b55ae

**Comment by nakano15** [comment]
That bug keeps returning with new methods to trigger it.
I added that to my todo list, so tomorrow I can check it out.

**Comment by nakano15** [comment]
Fixed. Asking companions mounted on your character to lift your character will no longer cause them to take flight.
Now, the companion will dismount before doing the action.
