### ISSUE TITLE
liebre sticks to behind the player when delivering souls

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#46]
pretty much just that ask him to deliver and he just sticks behind the player with very slight gravity also sorry for the moonling attack in the vid heh...

https://github.com/nakano15/terraguardians/assets/89364836/480879ce-036e-4444-b610-8fe80e605d94

**Comment by nakano15** [comment]
Oh yeah, I saw that issue too. I'm investigating why that's happening.

**Comment by nakano15** [comment]
I'm pretty sure this issue is fixed by now, so I'm closing it.
