### ISSUE TITLE
liebres plasma body no longer seems to render in the dark

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#48]
as simple as that i updated to the latest version and his plasma body stopped rendering in the dark
![image](https://github.com/nakano15/terraguardians/assets/89364836/3b6cf79a-22cb-45b1-b2a4-ddae3224d245)
![image](https://github.com/nakano15/terraguardians/assets/89364836/d860f799-0cfe-43ee-b1d2-a6bb048f6a12)

**Comment by nakano15** [comment]
I actually didn't had noticed that.
I noticed that his mouth no longer opens when pulling a soul, but the plasma disappearing I didn't.
I'll investigate that out.

**Comment by AnukWarrior** [comment]
oh yeah i noticed the mouth part too it happened when tmodloader had its last stable update i think the plasma body however i noticed stopped rendering when glen came back

**Comment by nakano15** [comment]
I had messed up on the flags checking, and made his plasma and mouth invisible whenever he was visible.
Fix is coming next update.
