### ISSUE TITLE
dismissing companions inside the companion list is now ocassionaly breaking and preventing from dismissing 

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#49]
note im unsure if it is linked to being a buddy with a diffrant companion

https://github.com/nakano15/terraguardians/assets/89364836/be0017f6-17f2-440c-adab-ef3825a5769b

**Comment by nakano15** [comment]
I will have to investigate further why that happens.
I remember having that issue happening before to me, but for now, it haven't repeated yet.

**Comment by AnukWarrior** [comment]
if it does help this bug happened as soon as i summoned daphne after that i noticed this happening

**Comment by AnukWarrior** [comment]
just updated the mod and now the bug has stopped intresting...

**Comment by nakano15** [comment]
That explains why I wasn't being able to trigger it, haha.
