### ISSUE TITLE
asking liebre to deliver souls while bond merged causes weird clipping

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#50]
also intrestingly as a side note his plasma body does render dispite it being a bit broken when doing this

https://github.com/nakano15/terraguardians/assets/89364836/c8b9e259-2bc6-404f-aacd-fdb3ffb5046a

**Comment by nakano15** [comment]
LOL!
And yeah, I forgot about the possibility of the player controlling Liebre when delivering souls.
Gladly the player got back from the gatekeeper with him heh.

**Comment by nakano15** [comment]
Fixed. Also, you will no longer be able to move while he's doing the delivery.
