### ISSUE TITLE
The Player Cant Aim a Companions Weapon When Bond-Merged

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#51]
https://github.com/nakano15/terraguardians/assets/89364836/3d35be4a-4baa-4819-bed6-7586363c5974

**Comment by nakano15** [comment]
Wops. Seems like my attempt at fixing a issue with Terraria Overhaul actually created a new issue.
I'll see to fixing that.

**Comment by nakano15** [comment]
Fixed. The fix should be coming soon.
