### ISSUE TITLE
companions inventorys get reset when spawned as a starter companion in a new world?

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#52]
from what i noticed from generateing many worlds for something my companions inventorys are getting reset alot of the ones who spawned in with the world has lost the gear i gave (that was alot of solar armor down the drain)

**Comment by nakano15** [comment]
Uh oh. I'll need to investigate that tomorrow.

**Comment by nakano15** [comment]
Fixed. Update has been sent already too.
