### ISSUE TITLE
The Depths + Terraguardians compat issue in drunk worlds

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#8]
for some reason depending on where certain companions are located on the world either right or left of the middle of the world that contains either depths or underworld it seems to load either the depths or underworld biome instead of only loading the depths or underworld biome for where the main player is at causing this to happen

![image](https://github.com/nakano15/terraguardians/assets/89364836/7c2af5d4-9119-4da5-90c5-f5c8cf5f89b7)

![image](https://github.com/nakano15/terraguardians/assets/89364836/c68cdab3-15e4-422a-b221-bd1b7d573e48)

**Comment by nakano15** [comment]
Odd. I thought I fixed that issue.
Is the mod updated for you?

**Comment by AnukWarrior** [comment]
yes its as up to date as possable via steam right now

**Comment by nakano15** [comment]
Wait, The Depths is a mod?
If is, I recommend letting the developer know of the issue.

**Comment by AnukWarrior** [comment]
yeah i have contact with the depths main dev i could ask if its something he can fix on his end

**Comment by AnukWarrior** [comment]
Lion8Cake the depths main dev has given us the link to the code that registers what side of the world the player is on
https://github.com/Lion8cake/TheDepths/blob/0bf4e664e34043bb66493ad8de887e6fca6a7260/Worldgen/TheDepthsWorldGen.cs#L43

**Comment by nakano15** [comment]
![image](https://github.com/nakano15/terraguardians/assets/1460392/5de2958e-060d-471d-bdbb-6c1718d7045a)
I believe I managed to fix that.
Potential fix coming next update.
