### ISSUE TITLE
TWAILA + Terraguardians compat issue

### ISSUE THREAD

**Issue by AnukWarrior** [nakano15/terraguardians#9]
as it seems TWAILA prioritizes the companion cursors making it so that seeing blocks/npcs that the players cursor is hovering on almost impossable

![image](https://github.com/nakano15/terraguardians/assets/89364836/8cb1ff6d-dce8-444e-9342-adbe3c515bf8)
my cursor is hovering over a grass block but instead TWAILA is showing a wooden table that a companion has their cursor over instead

**Comment by nakano15** [comment]
Known issue.
Ore Excavator also suffers from the same issue.
Maybe better let the modder who made TWAILA, whatever that is, know about this issue.

**Comment by nakano15** [comment]
I don't think I can fix this from my side, since might be related to how the companions bypasses themselves as the player.
Probably a good idea is let the developer of TWAILA know of this issue.

**Comment by AnukWarrior** [comment]
i found the github for TWAILA maybe this could help
https://github.com/Jadams505/Twaila

**Comment by nakano15** [comment]
Nope, still can't make it work...

**Comment by AnukWarrior** [comment]
havent realy had any progress with this so ill close it
